export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const INIT_LIST = 'INIT_LIST'
export const MENU_BAR = 'MENU_BAR' //菜单栏左滑
export const CHANGE_CHARTS = 'CHANGE_CHARTS' //图表
export const CHANGE_LINECHARTS = 'CHANGE_LINECHARTS' //折线图表
export const CHANGE_PIECHARTS = 'CHANGE_PIECHARTS' //饼状图
export const ORDER_TABLE = 'ORDER_TABLE' //订单
export const CHANGE_SHOW_STATUE = 'CHANGE_SHOW_STATUE' 
export const CLIENT_INFO = 'CLIENT_INFO' //客户信息
export const SYSTEM_DATA = 'SYSTEM_DATA' //系统数据
export const PROVINCE_DATA = 'PROVINCE_DATA' //省市区数据
export const SERVICE_ENTERPRISE = 'SERVICE_ENTERPRISE' //业务企业数据
export const SERVICE_COMPONENT = 'SERVICE_COMPONENT' //业务成分数据
export const SERVICE_DRAW = 'SERVICE_DRAW' //业务提取物数据
export const ADD_DATA = 'ADD_DATA' //添加枚举类型数据
export const UPDATE_DATA = 'UPDATE_DATA' //修改枚举数据
export const DELETE_SHOW_STATUE = 'DELETE_SHOW_STATUE' //删除系统数据
export const BREED_DATA = 'BREED_DATA' //药材列表
export const ADD_BREED_DATA = 'ADD_BREED_DATA' // 新增药材数据
export const UPDATE_BREED_DATA = 'UPDATE_BREED_DATA' // 修改药材数据
export const UPDATE_SPEC_DATA = 'UPDATE_SPEC_DATA' // 修改药材规格
export const DELETE_BREED_DATA = 'DELETE_BREED_DATA' // 删除breed信息
export const DELETE_SPECS_DATA = 'DELETE_SPECS_DATA' // 删除breed 相关信息
export const CATEGORY_DATA = 'CATEGORY_DATA' // 获取品种分类
export const ADDSPEC_DATA = 'ADDSPEC_DATA' // 新增药材规格
export const ADD_LOCAL_DATA = 'ADD_LOCAL_DATA' // 新增药材产地
export const ADD_ALIAS_DATA = 'ADD_ALIAS_DATA' // 新增药材别名
export const ADD_UNIT_DATA = 'ADD_UNIT_DATA' // 新增药材单位
export const BREED_DETAIL_DATA = 'BREED_DETAIL_DATA' //breed详细数据
export const SERVICE_ENTERPRISE_DETAIL = 'SERVICE_ENTERPRISE_DETAIL' //企业详细数据
export const ADD_CONTACT_DATA = 'ADD_CONTACT_DATA' //新增企业联系人
export const DELETE_CONTACT_DATA = 'DELETE_CONTACT_DATA' //删除企业联系人
export const UPDATE_CONTACT_DATA = 'UPDATE_CONTACT_DATA' //修改企业联系人
