export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const INIT_LIST = 'INIT_LIST'
export const MENU_BAR = 'MENU_BAR' //菜单栏左滑
export const CHANGE_CHARTS = 'CHANGE_CHARTS' //图表
export const CHANGE_LINECHARTS = 'CHANGE_LINECHARTS' //折线图表
export const CHANGE_PIECHARTS = 'CHANGE_PIECHARTS' //饼状图
export const ORDER_TABLE = 'ORDER_TABLE' //订单
export const CHANGE_SHOW_STATUE = 'CHANGE_SHOW_STATUE' 
export const CLIENT_INFO = 'CLIENT_INFO' //客户信息
export const SYSTEM_DATA = 'SYSTEM_DATA' //系统数据
export const PROVINCE_DATA = 'PROVINCE_DATA' //系统数据
export const SERVICE_ENTERPRISE = 'SERVICE_ENTERPRISE' //业务企业数据
export const SERVICE_COMPONENT = 'SERVICE_COMPONENT' //业务成分数据
export const SERVICE_DRAW = 'SERVICE_DRAW' //业务提取物数据
export const ADD_DATA = 'ADD_DATA' //添加枚举类型数据
export const SAVE_COMPANY_DATA = 'SAVE_COMPANY_DATA' //添加企业数据
export const UPDATE_DATA = 'UPDATE_DATA' //修改枚举数据
export const UPDATE_ENTER_DATA = 'UPDATE_ENTER_DATA' //修改企业数据
export const DELETE_SHOW_STATUE = 'DELETE_SHOW_STATUE' //删除系统数据
export const DELETE_COMPANY_STATUS = 'DELETE_COMPANY_STATUS' //删除企业数据
export const DELETE_COMPONENT_STATUS = 'DELETE_COMPONENT_STATUS' //删除成分数据
export const DELETE_DRAW_STATUS = 'DELETE_DRAW_STATUS' //删除提取物数据